#!/usr/bin/env python

"""
Inputs:
    1. Training data files
Outputs:
    'UserID \t Clicks \t Impressions \t Depth \t Position'
"""

import sys

for line in sys.stdin:

    # eliminate entrailing white spaces
    line = line.strip()

    # split for indexing]
    line = line.split('\t')

    # for data
    if len(line) > 3: # if instances
        click = line[2]
        impression = line[3]
        uid = line[-1]
        depth = line[7]
        position = line[8]
        print '%s\t%s\t%s\t%s' % (uid, click, impression, depth, position)
